# Generated by Django 3.1.2 on 2020-11-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201111_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auther_image',
            field=models.ImageField(null=True, upload_to='autherpic'),
        ),
    ]
