# Generated by Django 3.1.2 on 2020-11-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201111_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Highlight_explanation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='highlight_word',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
