# Generated by Django 3.1.2 on 2020-11-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201111_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='highlight_word',
            new_name='highlight_line',
        ),
    ]
