# Generated by Django 3.1.2 on 2020-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_highlighttopic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Highlighttopic_img',
            field=models.ImageField(blank=True, default='', upload_to='Highlighttopic_img'),
            preserve_default=False,
        ),
    ]
