# Generated by Django 3.1.2 on 2020-11-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201111_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
