# Generated by Django 3.1.2 on 2020-11-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201113_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
