# Generated by Django 3.1.2 on 2020-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_delete_subcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
