# Generated by Django 3.1.2 on 2020-11-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20201113_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
